;METADATA=(Diff=true, UseCommands=true)
[/Script/LivestreamingToolkit.OWLSettings]
bAutoLaunchNDIInstaller=False
bDisableHardwareEncoding=True
bSuppressLoginPopup=False
bUseApplicationLicense=False
bEnableOWLDemoLicences=True
bDemoLicencePopupDismissed=True
OWLOfflineAppData=
OWLCameraRenderOutputPath=D:/TrailSimulator/Saved/OWLCameraOutput

[/Script/Subsystems.BroadcastSettings]
SharedRT=/Game/MediaOutputWizard/LTV.LTV

[/Script/EngineSettings.GeneralProjectSettings]
CopyrightNotice=Copyright LTVProd 2026 All Rights Reserved.

